### ISSUE TITLE
Produce a set of standard Sagemaker Prometheus metrics

### ISSUE THREAD

**Issue by deepk2u** [aws-controllers-k8s/community#1055]
From the existing metrics, ACK controller publishes on `/metrics` URL, we don't get observability around Sagemaker jobs.

**What is needed?**

at minimum, there should be the following metrics:

For every job type, metrics should be published so that we can infer the following:
1. Total 
2. Successes
3. Failures
4. Duration

**What metrics do we want to track?**

```
sagemaker_job_submit_count{name="trainingjob"}
sagemaker_job_success_count{name="trainingjob"}
sagemaker_job_failure_count{name="trainingjob"}
sagemaker_job_success_execution_time_microseconds_sum{name="trainingjob"}
sagemaker_job_success_execution_time_microseconds_count{name="trainingjob"}
```

similarly for `processingjob`, `hyperparametertuningjob` etc.

**Comment by jaypipes** [comment]
Hi @deepk2u!

The metrics that are exposed by ACK service controllers are metrics about the service controller itself, including how many times AWS API calls were made. The metrics you refer to are *data plane metrics* for SageMaker. In other words, the ACK controller has no ability to provide these metrics for you because the ACK controller isn't executing the training jobs. The ACK controller is calling SageMaker APIs and SageMaker is executing those jobs on SageMaker's compute infrastructure.

I believe you will want to approach the SageMaker team about this feature request since they only support CloudWatch for data plane metrics.

https://docs.aws.amazon.com/sagemaker/latest/dg/training-metrics.html

Potentially, you might look into a CloudWatch -> Prometheus exporter utility like YACE (https://github.com/nerdswords/yet-another-cloudwatch-exporter) which would allow you to get the CloudWatch metrics that SageMaker stores for data plane metrics and place them into your Prometheus server.

cc'ing @akartsky and @surajkota from the SageMaker team to see if they have any other ideas.

Best,
-jay
