### ISSUE TITLE
Metadata and Spec are not patched when `rm.ReadOne` call fails

### ISSUE THREAD

**Issue by A-Hilaly** [aws-controllers-k8s/community#1230]
**Describe the bug**
Currently, the `resourceReconciler.createResource` function calls both of [`rm.Create` and `rm.ReadOne` functions sequentially](https://github.com/aws-controllers-k8s/runtime/blob/main/pkg/runtime/reconciler.go#L366-L378). In some APIs like the ECR one calling a `DescribeRepository` right after a `CreateRepository` can fail and return a `NotFound` error, which causes the controller to not patch the resources Spec and Metadata with the information initially returned by `CreateRepository` call. 

One solution would be to ignore the `NotFound` errors and proceed into Spec and resource Metadata patching. Another one would be to either implement a wait or retry mechanisms around the `ReadOne` call.

e.g
```go
	rlog.Enter("rm.ReadOne")
	observed, err := rm.ReadOne(ctx, latest)
	rlog.Exit("rm.ReadOne", err)
	if err != nil && err != ackerr.NotFound {
		return latest, err
	}
	if err == nil {
		// Take the status from the latest ReadOne
		latest.SetStatus(observed)
	}
``` 

**Steps to reproduce**

- Run ECR soak tests for a few hours.

**Expected outcome**

- The controller should populate the CR Spec with the registry ID returned by the ECR API.

**Environment**

* ecr-controller `v0.0.21`

**Comment by vijtrip2** [comment]
My 2 cents:

Why not lateInitialize `RegistryID` field ? I think that will solve the problem.

I think ignoring the `NotFoundError` from *ReadOne*(after *Create*) can introduce a rare status patching edge case and adding custom exponential retries on sdk *ReadOne* call seems an overkill here.

*Rare Status Patching EdgeCase*: If the `NotFoundError` is ignored from ReadOne(after Create), the `latest.Status` will not be up to date and reconciliation will finish without error (except when requeued based on Synced). The `Status` fields will only get updated correctly when resource is updated again by customer(triggering a reconciliation). However if we leave the current code as is, The `NotFoundError` will trigger another reconciliation. The second reconciliation will enter `Update` code block and even if No *Delta* for *Spec* fields is present between desired and latest, the correct status will be patched at the end of reconciliation loop. 

To solve the problem you mentioned regarding Spec patching for `RegistryID` field, if you add lateInitialization for this field, A *ReadOne* will happen after Update code block and correctly lateInitialize `RegistryID` field during second reconciliation loop.

You may ask what will happen if ReadOne returns `NotFoundError` during second reconciliation and the Create code block is executed again instead of Update. In that case, I expect the second create call for same resource will return `ResourceAlreadyExists` error and trigger another reconciliation until ReadOne returns correct response.

If you have concerns about polluting the controller logs with multiple reconciliation(I am not concerned about this since above case is rare), I will recommend may be adding custom wait after the sdkCreate call using custom hooks and not changing the current runtime behavior :)

**Comment by A-Hilaly** [comment]
> Why not lateInitialize RegistryID field ? I think that will solve the problem.

I run the soak tests with multiple new versions of the controller one of them added late initialization to the `RegistryID` field, still saw the same issue during the soak tests. I will re-run another one today and publish the findings here.

> The second reconciliation will enter Update code block and even if No Delta for Spec fields is present between desired and latest, the correct status will be patched at the end of reconciliation loop.

That exactly the problem, that was causing the ecr-controller to panic on startup for multiple hours. Triggering the `Update` code block causes the controller the panic because the update code path tries to use the `*RegistryID` which is a nil pointer.

>You may ask what will happen if ReadOne returns NotFoundError during second reconciliation and the Create code block is executed again instead of Update. In that case, I expect the second create call for same resource will return ResourceAlreadyExists error and trigger another reconciliation until ReadOne returns correct response.

Correct i saw this behavior multiple times with ReadOne/Create

>If you have concerns about polluting the controller logs with multiple reconciliation(I am not concerned about this since above case is rare), I will recommend may be adding custom wait after the sdkCreate call using custom hooks and not changing the current runtime behavior :)

Logs are not really concerning me here, but yeah adding a wait/requeue to sdkCreate is a good idea!

**Comment by vijtrip2** [comment]
> I will re-run another one today and publish the findings here.

👍 

> Triggering the Update code block causes the controller the panic because the update code path tries to use the *RegistryID which is a nil pointer.

Wouldn't a nil check for `RegistryID` handle this case? Just curious?

> Logs are not really concerning me here, but yeah adding a wait/requeue to sdkCreate is a good idea!

👍
