### ISSUE TITLE
Early resolve references returns a false positive error

### ISSUE THREAD

**Issue by RedbackThomson** [aws-controllers-k8s/community#1234]
**Describe the bug**
When using a resolved reference, the reconciler will throw a false positive just before it attempts to create the resource, due to the initial `ResolveReferences` setting the Spec fields. 

The initial [`ResolveReferences`](https://github.com/aws-controllers-k8s/runtime/blob/main/pkg/runtime/reconciler.go#L223) (called before `ReadOne`) resolves the `*Ref` fields on the object and sets the corresponding concrete values on the spec. Later, just before calling `Create`, the reconciler [calls `ResolveReferences` again ](https://github.com/aws-controllers-k8s/runtime/blob/a0caf01e3972f671a0258ec0bf68db53c6166a3b/pkg/runtime/reconciler.go#L359). This time, since the spec fields have already been populated, the method returns an error saying that `both resource reference wrapper and ID cannot be used together`. The resource is therefore never created, and this reconciler loops indefinitely. 

**Steps to reproduce**
1. Create any resource with a `*Ref` field, and populate that field with a valid value.

**Expected outcome**
The resource should be created successfully, without any reconciliation issues.

**Comment by vijtrip2** [comment]
> The resource should be created successfully, without any reconciliation issues.

This is the happy case and it is supported. APIGWv2 e2e tests validate this. However I did miss handling a common failure scenario(explained below). I will fix it ASAP. Sorry for the churn.

---

The second reference resolution should only happen once during the resource creation because when the finalizer is added and resource is patched, the resolved references get omitted. However if the resource is marked managed and create call fails initially for whatever reason, then during the second reconciliation finalizer won't be added again but the references will be resolved again, causing the validation error explained in the description.

I think the solution is very easy. Resolve references only after the finalizer is added, not on every create attempt. I will send out a PR very soon and make new runtime release as well.

**Comment by vijtrip2** [comment]
PR merged now. This issue should be fixed with next controller release.
