### ISSUE TITLE
Allow DBInstance to reference DBSubnet resources

### ISSUE THREAD

**Issue by ddmedvedev** [aws-controllers-k8s/community#1257]
**Describe the bug**
This bug is very similar to [this one](https://github.com/aws-controllers-k8s/community/issues/1228) but relates to RDS.
When creating RDS instance I'm trying to create such resources:
- secret (`apiVersion: v1, kind: Secret`)
- db subnet group (`apiVersion: rds.services.k8s.aws/v1alpha1, kind: DBSubnetGroup`)
- db instance (`apiVersion: rds.services.k8s.aws/v1alpha1, kind: DBInstance`)

Secret and db subnet group created both as Kubernetes objects and in AWS. But the db instance created only as object in Kubernetes cluster, not in AWS. 

`kubectl describe dbinstance.rds.services.k8s.aws/some-rds-instance -n some-namespace`
shows
`Message:               DBSubnetGroupNotFoundFault: DBSubnetGroup 'some-subnet-group' not found.
status code: 404, request id: 6c7c56ff-8189-4212-8cb0-9e5414735df9`
in Status section despite such subnet group already exists and 
`kubectl get dbsubnetgroup.rds.services.k8s.aws/some-subnet-group -n some-namespace`
shows subnet that created some time ago.

During this behaviour, RDS controller doesn't show any messages, except such one
`1.6498524065281293e+09	INFO	ackrt	created new resource	{"account": "xxx", "role": "", "region": "eu-west-1", "kind": "DBSubnetGroup", "namespace": "some-namespace", "name": "some-subnet-group", "is_adopted": false, "generation": 1}`

When I re-apply RDS db instance YAML - all works fine. Also, when I restart controller it reconciles and starting to create DB instance.

**Expected outcome**
RDS ACK controller should try to reconcile when DBSubnetGroup is successfully created.

**Environment**

* Kubernetes version 1.21
* Using EKS (yes/no), if so version? yes, eks.4
* AWS service targeted (S3, RDS, etc.) RDS

**Comment by jaypipes** [comment]
@vijtrip2 this can be solved by adding resource references to RDS controller's resources... for example, adding a `DBInstance.Spec.DBSubnetRefs` field in addition to `DBInstance.Spec.DBSubnetIDs`

**Comment by brucegucode** [comment]
Reading the description, I think it matches with existing expected behavior. 

1. RDS controller DBInstance CRD take `DBSubnetGroupNotFoundFault` as terminal exception, hence creation with non-exist subnet group will be considered terminal state. This aligns with RDS api call, https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html#API_CreateDBInstance_Errors , `DBSubnetGroupNotFoundFault` is `404` return code 
2. In such case, customer would need first create a DBSubnet group CRD and then create db instance using same name subnet group

**Comment by RedbackThomson** [comment]
@brucegucode Yes, both `DBSubnetGroupNotFoundFault` and `DBParameterGroupNotFound` are treated as terminal conditions (see [here](https://github.com/aws-controllers-k8s/rds-controller/blob/main/generator.yaml#L169-L170)). I think that these should be removed (and any other `*NotFound`) errors within all other custom resources, should be as well.

In order to be compliant with [GitOps](https://opengitops.dev/) - that is, being able to apply all of the resources at the same time and they all eventually are reconciled - we can't rely on users creating things in a specific order. Terminal conditions should be reserved for resources that reach a state where the `spec` of the resource needs to be updated. If a dependent resource is not found (eg. `DBSubnetGroup`), then we should continue to retry (with exponential backoff) until a) the dependency is found, or b) the user deletes the resource from K8s. 

This is the same scenario we have for when an IAM role or KMS key is not found. There is a chance that the user is creating it manually, or through another system, and it may be available after the K8s resource is created. In that case, we would hope the K8s resource is retried until the user has created that IAM role and then we can successfully complete the create request.

**Comment by brucegucode** [comment]
@RedbackThomson  I see your point here, we should allow k8s to constantly retry sync and try create db instance until the resource of `DBSubnetGroup` is available in k8s. hence we need to remove those terminal exceptions, also apply to other resources can be created in k8s as well

**Comment by brucegucode** [comment]
commit https://github.com/aws-controllers-k8s/rds-controller/commit/712a5b9c01131f309f0e31f6dcbd2c3ffaaae599 is merged, I'm ok to close this issue if there is no concern

**Comment by jaypipes** [comment]
Yup, thanks @brucegucode!
