### ISSUE TITLE
Add timestamp in test framework and convert epoch to human time in runtime logs

### ISSUE THREAD

**Issue by brucegucode** [aws-controllers-k8s/community#1329]
**Is your feature request related to a problem?**
I hope we can add timestamp in both runtime logs and e2e test logs. 

Here is an example of test run:
https://prow.ack.aws.dev/view/s3/ack-prow-logs/pr-logs/pull/aws-controllers-k8s_rds-controller/85/rds-kind-e2e/1535299554197377024 

1. The controller-runtime has epoch looks like , `1.654879082871827e+09`,  it would be great if we can convert it to human readable time 
2. For e2e test, if we can add timestamp at critical event, like make service call/start one test/end one test/ throw one exception. It would be pretty helpful for debugging purpose.

**Comment by vijtrip2** [comment]
PR https://github.com/aws-controllers-k8s/runtime/pull/98 updates the controller logs to use more human friendly timestamps.

**Comment by RedbackThomson** [comment]
While it would be nice to have structured logging output in the tests as well (I'll take note of this when working on the refactor stuff as part of #1359), I think the controller logs should suffice for the moment. We ship controller logs in the Prow e2e test runs if you want to see them for PRs, otherwise you can now look at your controller to get accurate timestamps as the tests run.
