### ISSUE TITLE
Subnet group VPC id specification in  ACK ElastiCache & MemoryDB 

### ISSUE THREAD

**Issue by shancz** [aws-controllers-k8s/community#1594]
**Is your feature request related to a problem?**
Yes. In ACK if you create an ElastiCache subnet group you can't specify the VPC id. This is a problem if you have more than one VPC. In the console option of both ElastiCache and MemoryDB when creating a subnet group the target VCP id can be passed in however this is not an option via ACK.

Here is the error message when creating a replication group:
  Conditions:
    Message:               InvalidParameterCombination: Subnet group [default] belongs to a different VPC [vpc-052817cec78e55362] than [vpc-000f39e7a39146442]

The cache subnet group belongs has to belong to the default VPC. This is not always the case.

**Describe the solution you'd like**
The ACK api that creates the subnet group should accept a target VPC ID.

**Describe alternatives you've considered**
No work around exists.

**Comment by kumargauravsharma** [comment]
The create replication group API accepts Amazon VPC security groups and subnet group. Create cache subnet group API accepts a list of VPC subnet IDs for the cache subnet group.

References:
* https://awscli.amazonaws.com/v2/documentation/api/latest/reference/elasticache/create-replication-group.html
* https://awscli.amazonaws.com/v2/documentation/api/latest/reference/elasticache/create-cache-subnet-group.html

From the the error message in the issue description, it seems that the VPC for the security groups and the VPC for the subnet ids in the subnet group are different. Due to this, the create replication group is returning the corresponding error message.

The create replication group is expected to succeed if the Amazon VPC security groups and VPC subnet IDs for the cache subnet group belong to the same VPC.
