### ISSUE TITLE
EKS Service Controller

### ISSUE THREAD

**Issue by jicowan** [aws-controllers-k8s/community#16]
## New ACK Service Controller

Support for Amazon EKS

### List of API resources

List the API resources in order of importance to you:

* [Cluster](https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateCluster.html)
* [Nodegroup](https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateNodegroup.html)
* [FargateProfile](https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateFargateProfile.html)

**Comment by mhausenblas** [comment]
I'm glad to see https://github.com/jicowan/fargate-operator happening and would be interested in feedback, as you roll it out and deploy it @jicowan.

**Comment by jlpettersson** [comment]
How is using this different from using AWS provider for [Kubernetes Cluster API](https://github.com/kubernetes-sigs/cluster-api)?

**Comment by rothgar** [comment]
@jlpettersson Cluster API does a lot of really cool things and is designed to be a generic way to create Kubernetes clusters. It makes some different design decisions with that goal in mind. Some include

- Cluster API is treated as your source of truth for all infrastructure. This means things like the [cluster autoscaler](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler) need to be configured to use cluster api instead of AWS ASGs.
- Generic Kubernetes clusters rely on running more services in the cluster and not relying on integrations from the cloud provider. Things like metrics and logging will probably need to run inside Kubernetes instead of using services like CloudWatch
- IAM permission for controllers like CAPA will need to be more broad than EKS controller because CAPA is responsible for setting up everything needed for the cluster (VPC, gateway, etc)

With an EKS ACK controller you will get all of the configuration flexibility of the EKS api (including things like managed node groups and fargate) with limited IAM scope. You also don't need to run all of the other controllers if all you want is a way to provision an EKS cluster.

I hope that clears up some of the confusion on how the two are similar and different.

**Comment by mhausenblas** [comment]
Nice explanation Justin, thanks. Care to turn it into an [FAQ item](https://aws.github.io/aws-controllers-k8s/community/faq/)?

**Comment by agill17** [comment]
I have also attempted to try this out for managing dynamic stateless workload use cases I have: https://github.com/agill17/eks-fargate-controller

**Comment by mikestef9** [comment]
Closing as this service controller has graduated to GA. Separate issues can be opened to discuss specific follow on topics on the controller.
