### ISSUE TITLE
Propagate NodeGroup tags to ASG

### ISSUE THREAD

**Issue by matheushent** [aws-controllers-k8s/community#1630]
**Is your feature request related to a problem?**
The basic idea os the feature request is to be able to propagate the tags defined in a NodeGroup resource (talking about the EKS controller) to the ASG created to manage the node group.

The motivation behind it is to be able to scale the node group from 0. According to [1] and [2], when there's taints applied to the node group, it cannot be discovered from the Launch Configuration, so it is needed to tag the ASG accordingly (check [1] for a concise example).

[1] https://aws.github.io/aws-eks-best-practices/cluster-autoscaling/#scaling-from-0
[2] https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#auto-discovery-setup

**Describe the solution you'd like**
I want the exact tags I set in the NodeGroup definition to be propagated to the ASG group. Example:

Let's say I set the following tag in my node group definition:
```yaml
tags:
  k8s.io/cluster-autoscaler/node-template/taint/spotInstance: "true:PreferNoSchedule"
```

I want the exact same tag to be applied to the resulting ASG after created.

**Describe alternatives you've considered**
Perhaps to have an ASG resource in the EC2 controller with some flag such as `import: true` to tell the controller the resource already exists so I just want to patch it.

**Comment by RedbackThomson** [comment]
I can understand how this would be applicable, but I think unfortunately this suggestion runs counter to one of the fundamentals of ACK. We designed the controllers so that an ACK controller only uses the SDK for whichever service it manages, and no others. That is, the EKS controller will only access EKS APIs. Your suggestion here would require that the EKS controller makes calls to the ASG APIs. 

The only way I can envision this working is whereby we have a workflow that adopts the ASGs that were created and then we update their tags. This would require the ASG controller be installed, and that the ASG controller supports creating these resources. Currently we don't even have an ASG controller - so that is the first step.

**Comment by matheushent** [comment]
@RedbackThomson if I understood correctly, there's no way to get this done, right? Because the EKS controller would need to make calls to the ASG controller and vice-versa.

Despite that, I believe this feature would be key to follow the EKS best practices (scaling from 0) and to save some good money sometimes xD. Do you have any other suggestion to get it going?

**Comment by RedbackThomson** [comment]
> Because the EKS controller would need to make calls to the ASG controller and vice-versa.
Correct. Not with the tools provided by the ACK project.

Perhaps once the ASG controller supports the node group resources, some combination of adopting those resources and modifying their tags would be sufficient? That's probably my best guess for now.
