### ISSUE TITLE
ACK for Sagemaker keeps reconciling even if validation exception occurs.

### ISSUE THREAD

**Issue by rachitchauhan43** [aws-controllers-k8s/community#1656]
**Describe the bug**

We are using ACK Sagemaker controller version v0.4.1. One thing we are noticing is that whan submitting a `TransformJob` and if it has Generate Name like this one `prosifter-batch-pipeline-sbctd-inference-`  then we see a ValidationException on describing that job using kubectl:
```
Message:               ValidationException: 1 validation error detected: Value 'prosifter-batch-pipeline-sbctd-inference-' at 'transformJobName' failed to satisfy constraint: Member must satisfy regular expression pattern: ^[a-zA-Z0-9](-*[a-zA-Z0-9]){0,62}
```

**Steps to reproduce**
Submit a `TransformJob` that ends up with `Generate Name` ending with `-` and that will yield ValidationException.

**Expected outcome**
Controller should reject the request in the first place and mark the job as FAILED instead of trying to reconcile.

**Environment**

* Kubernetes version: v1.22.15-eks-fb459a0
* Using EKS (yes/no), if so version?  Yes
* AWS service targeted (S3, RDS, etc.) Sagemaker

**Comment by RedbackThomson** [comment]
While this behaviour is annoying, I don't believe this is a bug. The SageMaker controller previously had `ValidationException` as a `Terminal` condition trigger. However, some validation exceptions can be retried and will eventually succeed. For those cases, it's best if we treat them as `Recoverable` conditions. Since we can't discriminate between different types of `ValidationException` messages, they all have to be marked `Recoverable`. 

>  Controller should reject the request in the first place and mark the job as FAILED instead of trying to reconcile.
This probably isn't the status we would set even if the job reaches a `Terminal` condition, since `FAILED` implies the job ran and didn't succeed. Instead, these jobs did not even begin. Hence we leave their status undefined.

**Comment by surajkota** [comment]
Hi @rachitchauhan43, thanks for the feedback. @RedbackThomson is correct, this is not a bug. We had tried going down the path of string comparison based on error message but it is hard to maintain and is not robust. We couldn't establish a pattern to these terminal and non terminal type of Validation errors.

That being the current state, @aws-controllers-k8s/runtime-maintainer one thing which can alleviate this issue to some extent is if we add the SDK client side validation to CRD fields using `kubebuilder:validation`, `api-2.json` file has this information

```
    "TransformJobName":{
      "type":"string",
      "max":63,                                        --> +kubebuilder:validation:MaxLength
      "min":1,                                         --> +kubebuilder:validation:MinLength
      "pattern":"^[a-zA-Z0-9](-*[a-zA-Z0-9]){0,62}"    --> +kubebuilder:validation:Pattern
    },
```

[e.g. from **old** sagemaker operator](https://github.com/aws/amazon-sagemaker-operator-for-k8s/blob/master/api/v1/trainingjob/trainingjob_types.go#L59)

I have created an issue for this https://github.com/aws-controllers-k8s/community/issues/1657

Hope this helps
