### ISSUE TITLE
Code generator generates CloudFormation inconsistent field name breaking initialisms logic

### ISSUE THREAD

**Issue by embano1** [aws-controllers-k8s/community#1666]
**Describe the bug**
PR https://github.com/aws-controllers-k8s/pkg/pull/11 attempted to fix an issue with the generated field names for the EventBridge `rule` (`Target`) resource (specifically fields `sql` in `RedshiftDataParameters` and `AWSvpcConfiguration` in `NetworkConfiguration`). 

The fix and tests for `sql` worked. However, the generated `types.go` struct for `NetworkConfiguration` is 

```go
// This structure specifies the network configuration for an ECS task.
type NetworkConfiguration struct {
	// This structure specifies the VPC subnets and security groups for the task,
	// and whether a public IP address is to be used. This structure is relevant
	// only for ECS tasks that use the awsvpc network mode.
	AWSvpcConfiguration *AWSVPCConfiguration `json:"awsvpcConfiguration,omitempty"`
}
```

Whereas the actual CloudFormation [definition](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-events-rule-networkconfiguration.html) is

```json5
{
  "AwsVpcConfiguration" : AwsVpcConfiguration
}
```

Adding this case to `names_test.go` actually breaks the unit tests

```go
{"AWSvpcConfiguration", "AWSVPCConfiguration", "awsVPCConfiguration", "aws_vpc_configuration", "awsvpcconfiguration"},
```

This logic is not handled in `normalizeInitialisms` and I think it should actually be a change in the code generator so that `AWSvpcConfiguration` becomes `AWSVpcConfiguration` as per the CloudFormation field. 

Since my understanding of this logic is minimal, I'm not sure which way to chose to fix the issue as it could break other controllers.

cc/ @RedbackThomson @A-Hilaly @jaypipes

**Comment by jaypipes** [comment]
We deliberately do not use the CloudFormation name because the CloudFormation names do not adhere to [Go initialism naming conventions](https://github.com/golang/go/wiki/CodeReviewComments#initialisms). The `pkg/names` package enforces renaming for those initialism naming conventions and for the Golang exported variable/field naming requirements (starting with a capital letter...).

> Adding this case to names_test.go actually breaks the unit tests

I don't know how "AWSvpcConfiguration" is being determined from the original "AwsVpcConfiguration". I added [unit tests](https://github.com/aws-controllers-k8s/pkg/blob/67260c9b08f93376f2abcb2a769f2171e82f2869/names/names_test.go#L39-L41) for three different variations:

```go
		{"AwsVpcConfiguration", "AWSVPCConfiguration", "awsVPCConfiguration", "aws_vpc_configuration", "awsvpcconfiguration"},
		{"AWSVpcConfiguration", "AWSVPCConfiguration", "awsVPCConfiguration", "aws_vpc_configuration", "awsvpcconfiguration"},
		{"AWSVPCConfiguration", "AWSVPCConfiguration", "awsVPCConfiguration", "aws_vpc_configuration", "awsvpcconfiguration"},
```

I am a bit stumped on where AWSvpcConfiguration is coming from.

**Comment by A-Hilaly** [comment]
This is super weird, the `type.go` template is correctly using `names.Camel` https://github.com/aws-controllers-k8s/code-generator/blob/main/templates/apis/type_def.go.tpl#L10 .

**Comment by A-Hilaly** [comment]
Fixed in https://github.com/aws-controllers-k8s/pkg/pull/12
/close
