### ISSUE TITLE
AdoptedResource for KMS Alias doesn't work

### ISSUE THREAD

**Issue by joaquinservetto** [aws-controllers-k8s/community#1746]
**Describe the bug**
AdoptedResources of group "kms.services.k8s.aws" and type "Alias" get stuck in a resource found error

**Steps to reproduce**
1- Deploy the KMS controller
2- Create a KMS key with an Alias
3- Create in the same cluster an AdoptedResource of type Alias and set the alias name in the nameOrID parameter.

**Expected outcome**
I expected the alias to be adopted but instead I see the AdoptedResource in this state:
```
    Message:  resource not found
    Status:   False
```
And the following logs in the controller: 
```
2023-03-22T13:37:14.590Z	INFO	adoption.adopted-reconciler	starting adoption reconciliation	{"target_group": "kms.services.k8s.aws", "target_kind": "Alias", "namespace": "cloud-application-platform", "name": "oamapp-0022-test-kms-mig-alias", "generation": 8}
2023-03-22T13:37:14.646Z	ERROR	controller.adoptedresource	Reconciler error	{"reconciler group": "services.k8s.aws", "reconciler kind": "AdoptedResource", "name": "oamapp-0022-test-kms-mig-alias", "namespace": "cloud-application-platform", "error": "resource not found"}
```

**Environment**
Kubernetes version: 1.24
Using EKS: 1.24
AWS service targeted: KMS

**Comment by RedbackThomson** [comment]
I think adoption for aliases is a bit different to other resources because the AWS `Alias` resource uses the `TargetKeyId` field as the primary key, and `AliasName` as a secondary index. In retrospect, I think aliases should have been a property of the `Key` resource.

Regardless, I would try setting the alias key ID in the `nameOrID` field, and then under `additionalKeys` set `name: <your-alias-name>`. This should tell the controller to search for the alias within that target key's list. 

The reason we need the key ID as the primary key is because we can have the same alias across different keys, so we can't uniquely identify an alias by its name.

**Comment by RedbackThomson** [comment]
Upon further review of the [`sdkFind` method](https://github.com/aws-controllers-k8s/kms-controller/blob/a7cb83cd2805ec7872804d5b0f07f351a538c17f/pkg/resource/alias/sdk.go#L55) - which the `AdoptedResource` reconciler relies on to determine the spec of an object - the only field that it relies on is `Spec.Name`. Alias names must be unique within an account, so it's not possible for a reconciler to find two aliases with the same name but different target key IDs. In that case, we should update the `generator.yaml` to move the `is_primary_key: true` attribute from `TargetKeyId` to `Name`.

**Comment by joaquinservetto** [comment]
@RedbackThomson It's working now, thanks!
