### ISSUE TITLE
Support IPv6 VPC

### ISSUE THREAD

**Issue by billyshambrook** [aws-controllers-k8s/community#1784]
**Is your feature request related to a problem?**

Currently it does not seem possible to create a VPC with IPv6 subnets. The IPv6 CIDR is allocated automatically for the VPC by AWS at the time of creation therefore you cannot deterministically know what the subnet CIDR ranges should be to define the Subnet resource.

**Describe the solution you'd like**

Some way to reference the VPC IPv6 CIDR in the Subnet resource. There also seems like some thought needs to be put into how the Subnet CIDR ranges will be calculated. In Terraform this can be done using the `cidrsubnet()` function but I don't see an existing equivalent in ACK.

**Describe alternatives you've considered**

I also looked at using IPAM to allocate IPv6 addresses but ran into the same kinda issue as you do not know ahead of time what CIDR range IPAM will allocate to your VPC.

**Comment by jaypipes** [comment]
> Currently it does not seem possible to create a VPC with IPv6 subnets.

Not quite sure what you mean by this... the [`Subnet`](https://aws-controllers-k8s.github.io/community/reference/ec2/v1alpha1/subnet/) resource Kind has a `spec.ipv6CIDRBlock` field that you can use to create an IPv6 subnet. The `Status` resource's `spec.vpcRef` field is used to refer to the [`VPC`](https://aws-controllers-k8s.github.io/community/reference/ec2/v1alpha1/vpc/) resource in which the subnet lies.

The `VPC` resource also has the `spec.ipv6CIDRBlock`, and `spec.ipv6NetmaskLength` fields which, instead of manually specifying IPv6 subnets, you can use to influence the automatic IPv6 IPAM behaviour.

Terraform's `cidrsubnet` function is a helper utility that can be used to generate an IP address from a CIDR string and an offset (from the CIDR's base address). This helper utility doesn't interact with AWS or any other cloud provider. To use something similar with ACK, you'd want to synthesize your YAML manifests using a tool like Kustomize or Helm and generate such IP addresses using a template function. After synthesizing your YAML, you feed it to ACK using `kubectl apply`
