### ISSUE TITLE
Ability to create RDS DB users.

### ISSUE THREAD

**Issue by rahtr** [aws-controllers-k8s/community#1793]
**Is your feature request related to a problem?**
For the [RDScontroller](https://github.com/aws-controllers-k8s/rds-controller), currently there is no automated way to create DB users. When using IAM based authentication, you need many steps before you can connect to the DB.

**Describe the solution you'd like**
Add a DB user custom resource which allows you to create DB users in the provisioned DB.

**Describe alternatives you've considered**
Currently we use a custom build operator for this-->https://github.com/adobe/proteus-aws-operator

**Comment by jaypipes** [comment]
Hi @rahtr. ACK controllers are specifically designed for control plane operations, not data plane operations. Creating DB users is a data plane operation since it creates RDBMS-specific database users against the specific RDS database endpoint (SQL). There is no AWS API for creating DB users. Instead, you use either SQL or an RDBMS-specific CLI tool to create them.

ACK controllers are generated from the AWS API definition and since DB users are not exposed as an AWS API, it's not possible for ACK controllers to implement these data plane operations.
