### ISSUE TITLE
Recommended IAM Policy for EKS Controller is missing IAM permissions needed for Fargate

### ISSUE THREAD

**Issue by aaroniscode** [aws-controllers-k8s/community#1821]
**What is the URL of the document?**

https://github.com/aws-controllers-k8s/eks-controller/blob/main/config/iam/recommended-inline-policy

**Which section(s) is the issue in?**

N/A

**What needs fixing?**

Recommended Policy needs to add:
- iam:PassRole
- iam:GetRole

When you create a `FargateProfile` custom resource, the controller needs `iam:PassRole` permissions to make the `CreateFargateProfile` API call because it's passing the Pod Execution Role to the Fargate Service.

The controller also needs `iam:GetRole` ... otherwise the EKS API call will fail with the error message:
```
InvalidRequestException: Failed to validate if SLR: AWSServiceRoleForAmazonEKSForFargate already exists due to missing permissions for 'iam:GetRole
```

**Additional context**

I can't find any mention of the requirement of `iam:PassRole` in the EKS documentation. But I did find a link to an AWS CDK issue that confirms the role is needed: https://github.com/aws/aws-cdk/issues/8546

**Comment by aaroniscode** [comment]
Closing as this was fixed in https://github.com/aws-controllers-k8s/eks-controller/pull/70

**Comment by wardviaene** [comment]
iam:PassRole could lead to privilege escalation if you can pass any role to any service. The code in CDK you referred to has a specific resource in the policy instead of "*": the Fargate execution role arn. Inputting the correct ARN is probably not possible here, as it's just a text file. To mitigate the risk that the role could be passed to another service (when the ack-controller has broader permissions), you could maybe add a condition to iam:PassRole:

```
            "Condition": {
                "StringEquals": {
                    "iam:PassedToService": "eks.amazonaws.com"
                }
            }
```
