### ISSUE TITLE
ELB / Enterprise Load Balancer service controller

### ISSUE THREAD

**Issue by mdykes-gw** [aws-controllers-k8s/community#481]
## New ACK Service Controller

Support for ELB / Enterprise Load Balancer 

### List of API resources

List the API resources in order of importance to you:

1) [resource 1]
1) [resource 2]

**Comment by jaypipes** [comment]
@mdykes-gw I'm fairly certain we won't be supporting classic Elastic Load Balancer (CLB/ELB) in ACK. The https://github.com/kubernetes-sigs/aws-load-balancer-controller project is where our Kubernetes integration with AWS load balancing services will live; it's unlikely that ACK will have much support for deep integration with Kubernetes Ingress and Service resources, since ACK service controllers only manage custom resources in the `services.k8s.aws` API Group, whereas projects like https://github.com/kubernetes-sigs/aws-load-balancer-controller provide implementations of core Kubernetes resources like Ingress and Service/Endpoint using AWS load balancing APIs.
