### ISSUE TITLE
Issue with codegen on GoCodeSetReadManyOutput as list type expect member but not members

### ISSUE THREAD

**Issue by kelvinwijaya** [aws-controllers-k8s/community#657]
**Describe the bug**
Error while running the code generator for Crossplane AWS Provider

```
Error: template: /aws-controllers-k8s/templates/crossplane/pkg/conversions.go.tpl:13:3: executing "sdk_find_read_many" at <GoCodeSetReadManyOutput .CRD "resp" "cr" 1 false>: error calling GoCodeSetReadManyOutput: List output shape had no field of type 'list'
exit status 1
```

**Steps to reproduce**
Run 'go run -tags codegen cmd/ack-generate/main.go crossplane sesv2 --provider-dir ../provider-aws'

**Expected outcome**
Go struct for the SES objects be generated succesfully

**Environment**

* Kubernetes version
* Using EKS (yes/no), if so version? yes
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b492541
9eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:40:13Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95
ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
* AWS service targeted (SES)

json struct in SES api model shown as `member`:

https://github.com/aws/aws-sdk-go/blob/419f55f10dad889afd5af70e5773f963683943cf/models/apis/sesv2/2019-09-27/api-2.json#L1055

```
 "AdditionalContactEmailAddresses":{
      "type":"list",
      "member":{"shape":"AdditionalContactEmailAddress"},
      "max":4,
      "min":1,
      "sensitive":true
    },
```

In the codegen logic, it expected MemberRefs `json:"members"`

https://github.com/aws/aws-controllers-k8s/blob/78ae68a01291f9cac0f3e0073979d1745b32f972/pkg/generate/code/set_resource.go#L300

**Comment by muvaf** [comment]
It seems like output of `EmailIdentityPolicy` resource query is a [`map` object](https://github.com/aws/aws-sdk-go/blob/v1.35.5/service/sesv2/api.go#L11705) which is not yet supported in ACK.

@kelvinwijaya do you actually need this resource? If not, I'd suggest having the following `apis/sesv2/v1alpha1/generator-config.yaml` file to ignore it:
```yaml
ignore:
  resource_names:
    - EmailIdentityPolicy
```

I just tested this and it seems the rest of the resources do work. I'd suggest ignoring all resources you don't currently need so that you don't have to implement all.

**Comment by kelvinwijaya** [comment]
Hi @muvaf 

Thanks for helping to clarify the resource that the code-generator is not supporting as of now.

EmailIdentityPolicy is considered an optional to enhance the security for access control. so this is not a show stopper as of now

It will be good to have map object support in future.

**Comment by prasek** [comment]
@jaypipes is this on the roadmap? ☝️

**Comment by jaypipes** [comment]
> @jaypipes is this on the roadmap? point_up

If the question is whether we will support generic `map` types in the code generator, the answer is yes. :) We actually support `map[string]string`. There is an issue with certain types being considered a `map[string]interface{}` (which is what the `aws.JSONValue` type is aliased to, which ends up being a problem for `controller-gen object` because it cannot figure out how to marshal that into JSON (ironic, yes...)

I have a related issue here: #119

**Comment by vijtrip2** [comment]
Please reopen if the issue still exists.
