### ISSUE TITLE
Documentation makes install info difficult to find

### ISSUE THREAD

**Issue by beezly** [aws-controllers-k8s/community#676]
**Describe the bug**
The installation instructions at https://aws.github.io/aws-controllers-k8s/user-docs/install/#helm-recommended are very difficult to discover.

**Steps to reproduce**
Try to find the installation instructions from the info at https://aws.github.io/aws-controllers-k8s/ (hint: Clicking user-docs>Install takes you to the WIP docs). Similarly, although outside this repo, the documentation at https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/ makes no mention of it either

**Expected outcome**
It should be easy for interested users to find the installation instructions.

**Environment**
N/A

**Comment by mhausenblas** [comment]
Thanks for pointing this out @beezly and apologies for the confusion. In a sense it's by design. The reasoning is that, in order for an ACK controller to [graduate to BETA](https://aws.github.io/aws-controllers-k8s/releases/), we require Helm chart support. As there is, at time of writing, no ACK controller in BETA yet (cf. [status](https://github.com/aws/aws-controllers-k8s/projects/1)), we haven't yet enabled the page in the menu yet. Hope this explains the background and I'll leave the ticket open for now until we have at least one ACK controller in beta and have enabled the menu item.

**Comment by RedbackThomson** [comment]
Now available at https://aws-controllers-k8s.github.io/community/user-docs/install/ (and through the "User Docs" link in the header nav)
