### ISSUE TITLE
CloudFormation service controller

### ISSUE THREAD

**Issue by cuppett** [aws-controllers-k8s/community#710]
## New ACK Service Controller

Support for CloudFormation.

To support integration with organizations which are migrating to Kubernetes or have largely adopted a technology and governance model around CloudFormation for managing their resources, a CloudFormation controller can help with this transition. Also, a general purpose CloudFormation controller would provide capability to support the entire library of AWS services able to be provisioned by the service ahead of development efforts for individual service CRDs over time. 

I have found a prior project demonstrating this concept and updated it here: https://github.com/cuppett/cloudformation-operator

Happy to continue to work on this and help within ACK

### List of API resources

List the API resources in order of importance to you:

1) Stack
1) StackChangeSet
1) StackSet

**Comment by jaypipes** [comment]
@cuppett Hello! We don't have any plans at this point to support a CloudFormation controller in ACK. There are a few reasons:

1) ACK service controllers consider themselves to be the owner and driver of state changes to the system, with Kubernetes/etcd storing the desired state and the ACK controller *actuating* the observed state to match the desired state. However, CloudFormation considers *itself* to be the owner and driver of state changes to the system. This fundamental disagreement between ownership causes issues in the design of a potential ACK service controller. This disagreement is made more critical due to point #2...

2) CloudFormation has its own definition of state that is different from ACK. Briefly, CloudFormation's idea of state is wrapped up in its concept of a CloudFormation Stack while ACK's idea of state is the finer-grained top-level resources in an AWS service API (such as an S3 Bucket). This difference in view of what "state" is and how it is tracked makes an ACK service controller generated implementation very difficult because essentially CloudFormation owns the resources defined in a particular Stack and while you can get some information about these resource state transitions using some APIs like (`DescribeStackResourceDrifts`](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_DescribeStackResourceDrifts.html), what APIs like `DescribeStackResourceDrifts` essentially do is reimplement the entire ACK service controller logic for an individual service controller -- but of course, on the AWS CloudFormation service-side.

3) Finally, while I recognize that there may be some value in an ACK CloudFormation service controller providing a migration path for existing CloudFormation users to use Kubernetes more directly, ACK really is designed for the Kubernetes user *first*, which means that the Kubernetes configuration language and resource model is what ACK controllers promote. The CloudFormation language (which is YAML-ish but also contains a ton of imperative and traditional programming-language constructs like conditionals and macros) is often what Kubernetes users are trying to get away from and are looking to the declarative-only standardized Kubernetes Custom Resource Definition and API machinery as a simpler alternative.

For heavy users of CloudFormation that wish to migrate to Kubernetes and ACK, I believe a better approach would be a command-line tool that consumed a CloudFormation Template and output Custom Resources that can be `kubectl apply`'d to a Kubernetes cluster with ACK controllers installed in it.

For users of CloudFormation that are relying on CloudFormation's server-side lifecycle management of groups of resources, these users can and should continue to use CloudFormation. If these users really want to move to a Kubernetes-native system that manages groups of related resources, they can also look at the [Crossplane project](https://crossplane.io).
Best,
-jay
