### ISSUE TITLE
Provide an option to configure a resource to requeue infinitely

### ISSUE THREAD

**Issue by mbaijal** [aws-controllers-k8s/community#826]
**Is your feature request related to a problem?**
Certain resources such as the SageMaker endpoint are not `Job` Type resources that "finish" but instead more `Service` like in the sense that they are maintained until deleted by the user. 
For such resources, we should continue to requeue the resource infinitely such that it always correctly reflects the server-side status. 

**Describe the solution you'd like**
Provide an option in the generator.yaml as - 
```
resources:
  ScalableTarget:
    is_infinite_requeue: true
    is_adoptable: false
```

The runtime should be able to see this flag on any object of such a type and keep adding the object back to the queue. 

**Describe alternatives you've considered**
Before the repo was split, [I had a working solution for this](https://github.com/mbaijal/aws-controllers-k8s/commit/c021ea6787d6bd914c58aa494299353bd32be582), but this is not well thought out, so as I am rethinking the solution we could do something like the following - 
1. Add a new conditionType which handles this use case. 
2. Add a field to the CRD spec itself and either
    - make it user-defined
    - or an immutable field with a value of our choosing. 
3. Another option could be to set the existing condition `ConditionTypeResourceSynced` either as - 
   - workaround - by using custom code for such resources to always set this condition to false 
   - design - allow setting this condition to a fixed value of `False`.

**Comment by surajkota** [comment]
how about `periodic_sync: <duration_in_seconds>` instead of `infinite_requeue: bool` ?

Option 1, considering the following should be true:
- requeue should not happen if the terminal condition is set
- should back off and retry instead of periodic requeue if there was an error during reconciliation

IMO we should drop option 2 since its not related to desired state of resource

option 3 seems like a workaround like you said, would like to hear what others think
setting resourceSynced can send a message that the resource is being currently modified by service whereas controller is just checking
also according to [current implementation](https://github.com/aws-controllers-k8s/runtime/blob/main/pkg/runtime/reconciler.go#L273-L279) if both terminal and resourceSynced are True, resourcesynced will take priority which should be changed I guess!

**Comment by jaypipes** [comment]
I like this idea a lot. I think I would prefer to structure the configuration like this, though:

```go
// ReconcileConfig describes options for controlling the reconciliation
// logic for a particular resource.
type ReconcileConfig struct {
    // RequeueOnSuccessSeconds indicates the number of seconds after which to requeue a
    // resource that has been successfully reconciled (i.e. ConditionTypeResourceSynced=true)
    // This is useful for resources that are long-lived and may have observable status fields
    // change over time that would be useful to refresh those field values for users.
    // This field is optional and the default behaviour of the ACK runtime is to not requeue
    // resources that have been successfully reconciled. Note that all ACK controllers will
    // *flush and resync their watch caches* every 10 hours by default, which will end up
    // causing ACK controllers to refresh the status views of all watched resources, but this
    // behaviour is expensive and may be turned off in future ACK runtime options.
    RequeuOnSuccessSeconds *int `json:"requeue_on_success_seconds,omitempty"`
}
```

@mbaijal you feel like giving the implementation of this a go? :)

**Comment by mbaijal** [comment]
Sure, sounds good! Thanks for the comments both :)

**Comment by mbaijal** [comment]
Fixed in PRs linked above.
