### ISSUE TITLE
New hook point for custom code for generating checkRequiredFieldsMissingFromShape implementation

### ISSUE THREAD

**Issue by ryansteakley** [aws-controllers-k8s/community#850]
**Is your feature request related to a problem?**
`requiredFieldsMissingFromReadOneInput` currently takes a required field that is set by default. This is an issue because some resources may have different required fields.

ex: For the SageMaker resource `ModelPackage`. There are versioned `modelPackage` and unversioned `modelPackage`, they both have a different required field being `ModelPackageGroupName `and `ModelPackageName`. `requiredFieldsMissingFromReadOneInput` will check for `ModelPackageName `and will infinitely recreate since it will never find the required field when a user attempts to make a versioned `modelPackage `which does not contain a `ModelPackageName`.

**Describe the solution you'd like**
Add new field to the `generator.yaml` file that will allow for fields to be specified to `requiredFieldsMissingFromReadOneInput`. Will need to change `checkRequiredFieldsMissingFromShape` to support this and add new format of type` x == nil && y == nil`. 

**Describe alternatives you've considered**
Open to alternatives.

**Comment by A-Hilaly** [comment]
IIRC - to solve this problem - we agreed that we need to implement something similar to:
```yaml
resources:
  ModelPackage:
    required_fields:
       oneOf:
         - ModelPackageGroupName
         - ModelPackageName
```
And eventually we can implement other options like `AllOf` and `anyOf`

**Comment by jaypipes** [comment]
> And eventually we can implement other options like `AllOf` and `anyOf`

Is `anyOf` the same as `oneOf`?

**Comment by jaypipes** [comment]
> IIRC - to solve this problem - we agreed that we need to implement something similar to:
> 
> ```yaml
> resources:
>   ModelPackage:
>     required_fields:
>        oneOf:
>          - ModelPackageGroupName
>          - ModelPackageName
> ```

@A-Hilaly I don't see how the above would actually allow code to be generated that solve the problem that @ryansteakley is describing.

What Ryan is describing is that the controller needs to know whether the `ModelPackage` is "versioned" in order to determine which field in the `DescribeModelPackagesInput` shape needs to be filled in. I don't think this is something we should add to the code generator other than allowing a hook point for controllers to override the `checkRequiredFieldsMissingFromShape` implementation for a specific resource.

The fact is that the SageMaker API has some straight-up awkward semantics that make a declarative model of its resources virtually impossible. We're going to have to rely on custom code in these cases I'm afraid. It's not something that I believe is going to be possible to introspect from the information we have in the api model JSON files.

**Comment by jaypipes** [comment]
@ryansteakley Can you change the issue summary and feature request to describe adding a new hook point for custom code for generating the `checkRequiredFieldsMissingFromShape` implementation please?

**Comment by A-Hilaly** [comment]
> Is `anyOf` the same as `oneOf`?

`anyOf` is one or more fields. `oneOf` is exactly one field

**Comment by A-Hilaly** [comment]
> @A-Hilaly I don't see how the above would actually allow code to be generated that solve the problem that @ryansteakley is describing.

@jaypipes my understanding from what ryan is describing, is that controllers need to make sure (validate) that we have at least one of the required fields, which in this case can be either `ModelPackageGroupName` or `ModelPackageName`. And currently for `ModelPackage` resource, the generated `requiredFieldsMissingFromReadOneInput` only verifies that `ModelPackageName` is present and doesn't check `ModelPackageGoupName`.

> What Ryan is describing is that the controller needs to know whether the ModelPackage is "versioned" in order to determine which field in the DescribeModelPackagesInput shape needs to be filled in. I don't think this is something we should add to the code generator other than allowing a hook point for controllers to override the checkRequiredFieldsMissingFromShape implementation for a specific resource.

I think that the logic of determining which field in the `DescribeModelPackagesInput` shape needs to be filled in, should Go inside `skdFind` code and not `requiredFieldsMissingFromReadOneInput`. And i'm not sure if how this can be done since `DescribeModelPackageInput` only have one field:

```go
// from https://raw.githubusercontent.com/aws/aws-sdk-go/main/service/sagemaker/api.go
type DescribeModelPackageInput struct {
	_ struct{} `type:"structure"`

	// The name or Amazon Resource Name (ARN) of the model package to describe.
	//
	// When you specify a name, the name must have 1 to 63 characters. Valid characters
	// are a-z, A-Z, 0-9, and - (hyphen).
	//
	// ModelPackageName is a required field
	ModelPackageName *string `min:"1" type:"string" required:"true"`
}
```

> The fact is that the SageMaker API has some straight-up awkward semantics that make a declarative model of its resources virtually impossible. We're going to have to rely on custom code in these cases I'm afraid. It's not something that I believe is going to be possible to introspect from the information we have in the api model JSON files.

I agree with the idea of having webhooks for complicated and wierd cases. I also think that having options like `oneOf`, `anyOf` and `allOf` to tune the behaviour of generated `requiredFieldsMissingFromReadOneInput` can be useful for sagemaker and other controllers
