### ISSUE TITLE
Unable to modify Parameters in the DBParameterGroup or DBClusterParameterGroup

### ISSUE THREAD

**Issue by phanimullapudi** [aws-controllers-k8s/community#868]
**Describe the bug**
DBClusterParameterGroup or DBParameterGroup not considering any Parameters and its values passed. No errors logged just ignoring the values.

**Steps to reproduce**

- Using DBParameterGroup ACK kind create below parametergroup and notice that value is not set.

`apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBParameterGroup
metadata:
  name: "ack-test-aurora-pg"
spec:
  name: "ack-test-aurora-pg"
  description: "Parameter Group for Aurora MySQL 5.7 - Created by ACK"
  family: "aurora-mysql5.7"
  parameters: {ParameterName='max_connections',ParameterValue=1000,ApplyMethod=immediate}`

**Expected outcome**

- Parameter has to set accordingly
- Errors should be thrown if any invalid values sent.

**Environment**

* Kubernetes version
v1.19.7
* Using EKS (yes/no), if so version? 
No
* AWS service targeted (S3, RDS, etc.)
RDS

**Comment by jaypipes** [comment]
@phanimullapudi after looking into this, it's going to be a bigger fix/change than I originally thought, with a bunch of custom code for handling parameters in a parameter group :(

Many of the issues highlighted in this blog post: https://tech.instacart.com/terraforming-rds-part-3-9d81a7e2047f were exposed when I went to fix what I thought was the main bug in the controller.

I'm taking this out of our current sprint (ending Thursday) and will need to spend probably a whole 2 week sprint on this specific issue. I will likely create a meta-issue on github for handling parameters for a DB parameter group, because there are a number of oddities about the RDS API in this area.
