### ISSUE TITLE
Panic throw when using build-controller-release.sh

### ISSUE THREAD

**Issue by ryansteakley** [aws-controllers-k8s/community#877]
**Describe the bug**
When using `build-controller-release.sh` a panic is thrown. This panic is not thrown when using `build-controller.sh`

This panic string is created at https://github.com/aws-controllers-k8s/code-generator/blob/818030180adbde6853e27935dc1e2e45450ad2b2/pkg/model/model.go#L153 however when using `build-controller.sh` it goes through the same code path but doesn't cause this panic to be thrown.

`panic: unknown additional Spec field with Op: UpdateModelPackage and Path: ApprovalDescription`

**Expected outcome**
Same behavior as `build-controller.sh` when consuming generator.yaml

**Environment**
Using codegen v0.6.0 release.

**Comment by RedbackThomson** [comment]
@ryansteakley and I diagnosed that this error was being introduced because running the `./scripts/build-controller-release.sh` file without specifying an `AWS_SDK_GO_VERSION` override, it will default to `AWS_SDK_GO_VERSION=v1.35.5` - which is probably different to the version used when building the APIs in the first place.

I will create a feature request to remove the default `AWS_SDK_GO_VERSION` and either read the value from the controller's `go.mod` file (preferred) or print an error and require it be specified by the user.
