### ISSUE TITLE
When pushing a git tag for release, we should auto-create a GH Release

### ISSUE THREAD

**Issue by jaypipes** [aws-controllers-k8s/community#904]
The [current instructions for releasing a service controller](https://aws-controllers-k8s.github.io/community/dev-docs/release/) finish the release by doing a `git tag && git push upstream main --tags`, which is all great and ends up triggering the Prow post-submit-release jobs which publish the Helm chart and controller binaries to ECR Public.

However, the `git push upstream main --tags` does *not* end up creating a Github Release with the name of the Git tag. It should.

We should add something to the post-submit-release job that constructs the Github Release wording and creates it.

**Comment by RedbackThomson** [comment]
I'd love to use something like [`gren`](https://github-tools.github.io/github-release-notes/). That way we have a consistent structure to our release notes!

I would also recommend that this be added as a Github workflow because Prow does not have privileges to access Github with these APIs (at the moment). Github workflows can be [given short-lived credentials]https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token) exactly for such tasks.
