### ISSUE TITLE
s3-controller helm chart: include CRDs

### ISSUE THREAD

**Issue by twz123** [aws-controllers-k8s/community#959]
**Is your feature request related to a problem?**
As far as I can see, the S3 controller's Helm chart doesn't have an option to include the CRDs. So, installing the Helm chart isn't enough, but requires the out-of-band install of the CRDs via some other mechanism.

**Describe the solution you'd like**
CRDs can be deployed as  part of the chart, e.g. via `crds.enabled` in values.yaml or similar. Maybe some extra flag is required to toggle the inclusion of `AdoptedResource`, which is not part of the S3 namespace, and could potentially be managed in another place.

**Describe alternatives you've considered**
To pull in the CRDs via some other mechanism (e.g. kustomize and a remote resource pointing at the git repo). Still, this is a workaround as it requires a second tool besides Helm.

**Comment by vijtrip2** [comment]
* Hi @twz123 , I can see the `crds` directory present [here](https://github.com/aws-controllers-k8s/s3-controller/tree/main/helm)
* I also validated that if i perform helm install, crds do get installed.
* I also validated that public ecr helm charts also include `crds` directory.
* If crds directory is present, helm will automatically install crds during helm install command. If you wish to skip them, there is also an option '--skip-crds'. [Helm Documentation](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you)

-----

If the issue is still existing for you, can you please provide the steps to reproduce the issue.

**Comment by twz123** [comment]
Hey @vijtrip2, thanks for your kind reply, Indeed, this was my bad, I was using helm template and completely overlooked the crd/ folder.
