### ISSUE TITLE
elasticloadbalancingv2 unable to generate

### ISSUE THREAD

**Issue by haarchri** [aws-controllers-k8s/community#985]
**Describe the bug**
in crossplane we are unable to generate elasticloadbalancingv2 
looks like naming issues between elasticloadbalancingv2 and elbv2 
also we see issues regarding go sdk version 1.37.10 - did we have trick to generate it ?

https://github.com/crossplane/provider-aws/issues/841

**Comment by RedbackThomson** [comment]
The code-generator now supports setting a different "model name" as part of the `generator.yaml` file - https://github.com/aws-controllers-k8s/code-generator/pull/216

See the `opensearchservice` generator file as reference - https://github.com/aws-controllers-k8s/opensearchservice-controller/blob/6b4a9e6aad9f15411f6c6380f05c27211466427b/generator.yaml#L1

Since the AWS SDK Go references the API as `elbv2`, your `model_name` should be `elasticloadbalancingv2`
