### ISSUE TITLE
apigatewayv2 controller v0.0.6 has problems for to run the pods

### ISSUE THREAD

**Issue by estebancatano** [aws-controllers-k8s/community#990]
**Describe the bug**
I'm try install the version v0.0.6 (This was release yesterday) for apigatewayv2 controller, but it is'not working for me.

helm install works fine, but the pods never starts, and the pod describe command (kubectl describe pod $POD_NAME -n $NAMESPACE) show an error.
![Captura de Pantalla 2021-09-28 a la(s) 12 41 11 p  m](https://user-images.githubusercontent.com/9955458/135138195-4fc504cc-cea9-4f33-ad43-d58d0f4dd7e5.png)

**Steps to reproduce**
I'm installing using this guide https://aws-controllers-k8s.github.io/community/docs/user-docs/install/.

export SERVICE=apigatewayv2
export RELEASE_VERSION=v0.0.6
export CHART_REF=$SERVICE-chart
export CHART_REPO=public.ecr.aws/aws-controllers-k8s/$CHART_REF
export CHART_PACKAGE=$CHART_REF-$RELEASE_VERSION.tgz

mkdir -p $CHART_EXPORT_PATH
helm pull oci://$CHART_REPO --version $RELEASE_VERSION -d $CHART_EXPORT_PATH
tar xvf $CHART_EXPORT_PATH/$CHART_PACKAGE -C $CHART_EXPORT_PATH

helm install ack-${SERVICE}-controller \
  $CHART_EXPORT_PATH/$SERVICE-chart \
  --namespace $NAMESPACE \
  --set serviceAccount.create=false \
  --set aws.region=$AWS_REGION

**Environment**

* Kubernetes version: 1.19
* Using EKS (yes/no), if so version?: eks.6
* AWS service targeted (S3, RDS, etc.): apigatewayv2

**Comment by jaypipes** [comment]
Hi @estebancatano! Would you mind pasting any log output from the failed controller Pod please? Thank you!

**Comment by vijtrip2** [comment]
Hi @estebancatano , Thanks for reaching out.

We have PR out for updating the install doc which shall be merged soon, But I can recommend you two updates that will make the controller install successfully for you.
1. Please use `--set aws.account_id` flag during helm install
2. Please also remove `serviceAccount.create=False` unless your default user has permission to read/write on APIGatewayv2 CRDs.

Again, apologies for the friction you faced because of our docs getting out of date. We are going to fix it ASAP.

**Comment by estebancatano** [comment]
Hi @vijtrip2 thanks for your answer, the problem was resolved with the flag `--set aws.account_id` 

Thanks!
